/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { Randomizer } from "../Randomizer";

export class Randomizer__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Randomizer {
    return new Contract(address, _abi, signerOrProvider) as Randomizer;
  }
}

const _abi = [
  {
    constant: true,
    inputs: [],
    name: "returnValue",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
];
