/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { RandomizerDAI } from "../RandomizerDAI";

export class RandomizerDAI__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): RandomizerDAI {
    return new Contract(address, _abi, signerOrProvider) as RandomizerDAI;
  }
}

const _abi = [
  {
    constant: true,
    inputs: [],
    name: "getBalance",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
];
