/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface Randomizer3Interface extends ethers.utils.Interface {
  functions: {
    "daiContract()": FunctionFragment;
    "getBalance()": FunctionFragment;
    "getBalance1()": FunctionFragment;
    "getBalance2()": FunctionFragment;
    "getBalance3()": FunctionFragment;
    "randomizerDAIContract()": FunctionFragment;
    "randomizerDAIContract2()": FunctionFragment;
    "returnHashStringClean()": FunctionFragment;
    "returnHashStringDynamic()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "daiContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBalance1",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBalance2",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBalance3",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "randomizerDAIContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "randomizerDAIContract2",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "returnHashStringClean",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "returnHashStringDynamic",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "daiContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBalance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBalance1",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBalance2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBalance3",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "randomizerDAIContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "randomizerDAIContract2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "returnHashStringClean",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "returnHashStringDynamic",
    data: BytesLike
  ): Result;

  events: {};
}

export class Randomizer3 extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: Randomizer3Interface;

  functions: {
    daiContract(overrides?: CallOverrides): Promise<[string]>;

    "daiContract()"(overrides?: CallOverrides): Promise<[string]>;

    getBalance(overrides?: CallOverrides): Promise<[BigNumber]>;

    "getBalance()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    getBalance1(overrides?: CallOverrides): Promise<[BigNumber]>;

    "getBalance1()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    getBalance2(overrides?: CallOverrides): Promise<[BigNumber]>;

    "getBalance2()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    getBalance3(overrides?: CallOverrides): Promise<[BigNumber]>;

    "getBalance3()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    randomizerDAIContract(overrides?: CallOverrides): Promise<[string]>;

    "randomizerDAIContract()"(overrides?: CallOverrides): Promise<[string]>;

    randomizerDAIContract2(overrides?: CallOverrides): Promise<[string]>;

    "randomizerDAIContract2()"(overrides?: CallOverrides): Promise<[string]>;

    returnHashStringClean(overrides?: CallOverrides): Promise<[string]>;

    "returnHashStringClean()"(overrides?: CallOverrides): Promise<[string]>;

    returnHashStringDynamic(overrides?: CallOverrides): Promise<[string]>;

    "returnHashStringDynamic()"(overrides?: CallOverrides): Promise<[string]>;
  };

  daiContract(overrides?: CallOverrides): Promise<string>;

  "daiContract()"(overrides?: CallOverrides): Promise<string>;

  getBalance(overrides?: CallOverrides): Promise<BigNumber>;

  "getBalance()"(overrides?: CallOverrides): Promise<BigNumber>;

  getBalance1(overrides?: CallOverrides): Promise<BigNumber>;

  "getBalance1()"(overrides?: CallOverrides): Promise<BigNumber>;

  getBalance2(overrides?: CallOverrides): Promise<BigNumber>;

  "getBalance2()"(overrides?: CallOverrides): Promise<BigNumber>;

  getBalance3(overrides?: CallOverrides): Promise<BigNumber>;

  "getBalance3()"(overrides?: CallOverrides): Promise<BigNumber>;

  randomizerDAIContract(overrides?: CallOverrides): Promise<string>;

  "randomizerDAIContract()"(overrides?: CallOverrides): Promise<string>;

  randomizerDAIContract2(overrides?: CallOverrides): Promise<string>;

  "randomizerDAIContract2()"(overrides?: CallOverrides): Promise<string>;

  returnHashStringClean(overrides?: CallOverrides): Promise<string>;

  "returnHashStringClean()"(overrides?: CallOverrides): Promise<string>;

  returnHashStringDynamic(overrides?: CallOverrides): Promise<string>;

  "returnHashStringDynamic()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    daiContract(overrides?: CallOverrides): Promise<string>;

    "daiContract()"(overrides?: CallOverrides): Promise<string>;

    getBalance(overrides?: CallOverrides): Promise<BigNumber>;

    "getBalance()"(overrides?: CallOverrides): Promise<BigNumber>;

    getBalance1(overrides?: CallOverrides): Promise<BigNumber>;

    "getBalance1()"(overrides?: CallOverrides): Promise<BigNumber>;

    getBalance2(overrides?: CallOverrides): Promise<BigNumber>;

    "getBalance2()"(overrides?: CallOverrides): Promise<BigNumber>;

    getBalance3(overrides?: CallOverrides): Promise<BigNumber>;

    "getBalance3()"(overrides?: CallOverrides): Promise<BigNumber>;

    randomizerDAIContract(overrides?: CallOverrides): Promise<string>;

    "randomizerDAIContract()"(overrides?: CallOverrides): Promise<string>;

    randomizerDAIContract2(overrides?: CallOverrides): Promise<string>;

    "randomizerDAIContract2()"(overrides?: CallOverrides): Promise<string>;

    returnHashStringClean(overrides?: CallOverrides): Promise<string>;

    "returnHashStringClean()"(overrides?: CallOverrides): Promise<string>;

    returnHashStringDynamic(overrides?: CallOverrides): Promise<string>;

    "returnHashStringDynamic()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    daiContract(overrides?: CallOverrides): Promise<BigNumber>;

    "daiContract()"(overrides?: CallOverrides): Promise<BigNumber>;

    getBalance(overrides?: CallOverrides): Promise<BigNumber>;

    "getBalance()"(overrides?: CallOverrides): Promise<BigNumber>;

    getBalance1(overrides?: CallOverrides): Promise<BigNumber>;

    "getBalance1()"(overrides?: CallOverrides): Promise<BigNumber>;

    getBalance2(overrides?: CallOverrides): Promise<BigNumber>;

    "getBalance2()"(overrides?: CallOverrides): Promise<BigNumber>;

    getBalance3(overrides?: CallOverrides): Promise<BigNumber>;

    "getBalance3()"(overrides?: CallOverrides): Promise<BigNumber>;

    randomizerDAIContract(overrides?: CallOverrides): Promise<BigNumber>;

    "randomizerDAIContract()"(overrides?: CallOverrides): Promise<BigNumber>;

    randomizerDAIContract2(overrides?: CallOverrides): Promise<BigNumber>;

    "randomizerDAIContract2()"(overrides?: CallOverrides): Promise<BigNumber>;

    returnHashStringClean(overrides?: CallOverrides): Promise<BigNumber>;

    "returnHashStringClean()"(overrides?: CallOverrides): Promise<BigNumber>;

    returnHashStringDynamic(overrides?: CallOverrides): Promise<BigNumber>;

    "returnHashStringDynamic()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    daiContract(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "daiContract()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getBalance(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getBalance()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getBalance1(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getBalance1()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getBalance2(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getBalance2()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getBalance3(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getBalance3()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    randomizerDAIContract(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "randomizerDAIContract()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    randomizerDAIContract2(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "randomizerDAIContract2()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    returnHashStringClean(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "returnHashStringClean()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    returnHashStringDynamic(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "returnHashStringDynamic()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
