export const deployConfigDetailsArray = [
  {
    name: "R4v3n",
    network: "sepolia",
    environment: "staging",
    adminACLContractName: "AdminACLV1",
    genArt721CoreContractName: "GenArt721CoreV3_Engine_Flex",
    tokenName: "r4v3n",
    tokenTicker: "R4V3N",
    startingProjectId: 0,
    autoApproveArtistSplitProposals: true,
    renderProviderAddress: "deployer",
    platformProviderAddress: "0xF2162BaCC9F76608bA4b11b1a6dac976ED463129",
    addInitialProject: false,
    doTransferSuperAdmin: true,
    newSuperAdminAddress: "0xF2162BaCC9F76608bA4b11b1a6dac976ED463129",
    renderProviderSplitPercentagePrimary: 10,
    renderProviderSplitBPSSecondary: 250,
    defaultVerticalName: "flex",
  },
];
