export const deployConfigDetailsArray = [
  {
    name: "Verisart",
    network: "sepolia",
    environment: "staging",
    adminACLContractName: "AdminACLV1",
    genArt721CoreContractName: "GenArt721CoreV3_Engine_Flex",
    tokenName: "Verisart Test",
    tokenTicker: "VERIS",
    startingProjectId: 0,
    autoApproveArtistSplitProposals: true,
    renderProviderAddress: "deployer",
    platformProviderAddress: "0x97FD319E3d5283296583035C5AdDef1e99e21a2E",
    addInitialProject: false,
    doTransferSuperAdmin: true,
    newSuperAdminAddress: "0x97FD319E3d5283296583035C5AdDef1e99e21a2E",
    renderProviderSplitPercentagePrimary: 10,
    renderProviderSplitBPSSecondary: 250,
    defaultVerticalName: "flex",
  },
];
