import { ethers } from "hardhat";

export const CONFIG_MERKLE_ROOT =
  ethers.utils.formatBytes32String("merkleRoot");
export const CONFIG_USE_MAX_INVOCATIONS_PER_ADDRESS_OVERRIDE =
  ethers.utils.formatBytes32String("useMaxMintsPerAddrOverride");
export const CONFIG_MAX_INVOCATIONS_OVERRIDE = ethers.utils.formatBytes32String(
  "maxMintsPerAddrOverride"
);

// expected revert messages
export const revertMessages = {
  onlyArtist: "Only Artist",
  maximumInvocationsReached: "Max invocations reached",
  invalidMaxInvocations: "Invalid max invocations",
  priceNotConfigured: "Price not configured",
  projectIdDoesNotExist: "Project ID does not exist",
  needMoreValue: "Min value to mint req.",
  noRenounceOwnership: "Cannot renounce ownership",
  onlyAdminACL: "Only Admin ACL allowed",
  onlyCoreAdminACL: "Only Core AdminACL allowed",
  onlyCoreAdminACLOrArtist: "Only Artist or Core Admin ACL",
  onlyMinterFilterACL: "Only MinterFilter AdminACL",
  onlyRegisteredCore: "Only registered core contract",
  onlyNonZeroAddress: "Only non-zero address",
  onlyNonZero: "Only non-zero",
  minterAlreadyApproved: "Minter already approved",
  mustSendCorrectAmount:
    "Must send amount greater than or equal to price per token",
  noMinterAssigned: "No minter assigned",
  onlyPreviouslyApprovedMinter: "Only previously approved minter",
  onlyApprovedMinters: "Only approved minters",
  onlyValidProjectId: "Only valid project ID",
  onlyAssignedMinter: "Only assigned minter",
  nonExistentKey: "EnumerableMap: nonexistent key",
  lengthOfArraysMustMatch: "TokenHolderLib: arrays neq length",
  onlyRegisteredNFTAddresses: "TokenHolderLib: address not registered",
  purchaseRequiresNFT: "Purchase requires NFT ownership",
  needMoreAllowance:
    "VM Exception while processing transaction: reverted with reason string 'ERC20: insufficient allowance",
  needMoreBalance:
    "VM Exception while processing transaction: reverted with reason string 'ERC20: transfer amount exceeds balance",
  ERC20TransferToZeroError: "ERC20: transfer to the zero address",
  ERC20MockBannedTransfer: "ERC20Mock: transfer to banned address",
  ERC20NotConfigured: "ERC20: payment not configured",
  ERC20NoEther: "ERC20: No ETH when using ERC20",
  ERC20NullAddress: "null address, only ERC20",
  ERC20NonNullSymbol: "only non-null symbol",
  panelAlreadyMinted: "Panel already minted",
  unexpectedHashSeed: "Unexpected token hash seed",
  inactiveFunction: "Inactive function",
  onlyFutureAuctionsOrZero: "Only future start times or 0",
  auctionTooShort: "Auction duration below minimum",
  onlyUnconfiguredProjects: "Only unconfigured projects",
  onlyConfiguredProjects: "Project not configured",
  noNextToken: "No next token",
  onlyGteStartTime: "Only gte project start time",
  insufficientInitialBid: "Insufficient initial bid",
  onlyNextTokenPopulated: "No next token, check max invocations",
  incorrectTokenId: "Incorrect target token ID",
  tokenNotBeingAuctioned: "Token ID does not match auction",
  auctionAlreadyEnded: "Auction already ended",
  bidTooLow: "Bid is too low",
  auctionNotInitialized: "Auction not initialized",
  auctionNotEnded: "Auction not yet ended",
  onlySameProject: "Only tokens in same project",
  noAuction: "No auction exists on project",
  nextTokenNotPopulated: "Next token not populated",
  onlyGte7000: "Only gte 7_000",
  onlyConfiguredAuctions: "Only configured auctions",
  halfLifeTooShort:
    "Price decay half life must be greater than min allowable value",
  noMidAuction: "No modifications mid-auction",
  onlyFutureAuctions: "Only future auctions",
  auctionNotStarted: "Auction not yet started",
  invalidDAPrices: "Auction start price must be greater than auction end price",
  noZeroHalfLife: "Half life of zero not allowed",
  tooShortAuction:
    "Auction length must be at least minimumAuctionLengthSeconds",
  notImplemented: "Not implemented",
  onlyDecreasingPrice: "Only monotonic decreasing price",
  onlyBeforeRevenuesWithdrawn: "Only before revenues collected",
  onlyGteBasePrice: "Only gte base price",
  onlyCompleteAuction: "Auction must be complete",
  onlyReduceSelloutPrice: "May only reduce sellout price",
  onlyNonZeroBasePrice: "Base price must be non-zero",
  revenuesAlreadyCollected: "Revenues already collected",
  auctionNotSoldOut: "Active auction not yet sold out",
  onlyNonZeroLatestPurchasePrice: "Only latestPurchasePrice > 0",
  noClaimToZeroAddress: "No claiming to the zero address",
  noPurchasesMade: "No purchases made by this address",
  reclaimingFailed: "Reclaiming failed",
  noZeroAddress: "No zero address",
  arrayLengthsMatch: "Array lengths must match",
  refundFailed: "Refund failed",
  renderProviderPaymentFailed: "Render Provider payment failed",
  onlyBeforePurchases: "Only before purchases",
};
