/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IDelegationRegistry } from "./IDelegationRegistry";
export * as factories from "./factories";
export { IDelegationRegistry__factory } from "./factories/IDelegationRegistry__factory";
