export const deployConfigDetailsArray = [
  {
    name: "Tender Flex",
    network: "sepolia",
    environment: "staging",
    adminACLContractName: "AdminACLV1",
    genArt721CoreContractName: "GenArt721CoreV3_Engine_Flex",
    tokenName: "TenderFlexV3",
    tokenTicker: "TENDER",
    startingProjectId: 0,
    autoApproveArtistSplitProposals: true,
    renderProviderAddress: "deployer",
    platformProviderAddress: "0xFdc45dae01d1F9EF394b33c227BA9489795d148B",
    addInitialProject: false,
    doTransferSuperAdmin: true,
    newSuperAdminAddress: "0xFdc45dae01d1F9EF394b33c227BA9489795d148B",
    renderProviderSplitPercentagePrimary: 10,
    renderProviderSplitBPSSecondary: 250,
    defaultVerticalName: "flex",
  },
];
