export const deployConfigDetailsArray = [
  {
    name: "Blind Gallery",
    network: "sepolia",
    environment: "staging",
    adminACLContractName: "AdminACLV1",
    genArt721CoreContractName: "GenArt721CoreV3_Engine_Flex",
    tokenName: "Blind Gallery",
    tokenTicker: "BLIND",
    startingProjectId: 0,
    autoApproveArtistSplitProposals: true,
    renderProviderAddress: "deployer",
    platformProviderAddress: "0xA0F3c892D9Ea86Ef0C0b0fe8C5e1727A93Da18D7",
    addInitialProject: false,
    doTransferSuperAdmin: true,
    newSuperAdminAddress: "0xA0F3c892D9Ea86Ef0C0b0fe8C5e1727A93Da18D7",
    renderProviderSplitPercentagePrimary: 10,
    renderProviderSplitBPSSecondary: 250,
    defaultVerticalName: "flex",
  },
];
