import WalletButton from "./(auth)/wallet-button";
import GlobalProviders from "./global-providers";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalProviders>
          <header className="w-full p-4 flex justify-end">
            <WalletButton />
          </header>
          {children}
        </GlobalProviders>
      </body>
    </html>
  );
}
